/* NemaFarms editorial design system — grounded imagery, clear buying journeys. */
(() => {
  const products = [
    {id:'chicken',no:'01',name:'Whole chicken',category:'POULTRY',image:'nemafarms-chicken-sticker.png',alt:'NemaFarms supplied chicken sticker artwork',title:'For the table.<br><em>And everyone around it.</em>',copy:'A Sunday gathering. A family favourite. The next dish on your menu. Bring the farm a little closer to your kitchen.',note:'Halal · Vegetarian fed · Farmed locally',disclosure:'Supplied sticker artwork. Confirm current pack details with the farm.',enquiry:'Whole chicken'},
    {id:'eggs',no:'02',name:'Farm egg crate',category:'EGGS',image:'client-eggs-brown.webp',alt:'A supplied photograph of brown farm eggs in a crate',title:'Little things.<br><em>Everyday possibilities.</em>',copy:'From the first meal of the morning to the last batch from the oven. Start a conversation about eggs for your home or business.',note:'Supplied farm photograph · For home kitchens & hospitality',disclosure:'Ask the farm to confirm current egg sizes and pack formats.',enquiry:'Egg crate'},
    {id:'produce',no:'03',name:'From the growing fields',category:'PRODUCE',image:'client-produce-bed.webp',alt:'A supplied photograph of a growing bed at NemaFarms',title:'In the ground.<br><em>With the seasons.</em>',copy:'Good food begins long before it reaches the table. Explore the growing fields and the food forest, then ask what is available now.',note:'Seasonal availability · Enquire with the farm',disclosure:'Supplied farm photograph.',enquiry:'Produce'}
  ];
  const arrow='<span aria-hidden="true">↗</span>';
  function panel(p){return `<div class="at-product-photo ${p.id==='produce'?'at-photo-crop':''}"><span class="at-photo-id">N° ${p.no} — ${p.category}</span><img src="assets/${p.image}" width="1122" height="1402" alt="${p.alt}" loading="lazy"><button class="at-quick" data-quick-product="${p.id}" aria-label="Quick view: ${p.name}">A closer look <span>＋</span></button></div><div class="at-product-copy"><p class="at-kicker">THE NEMAFARMS COLLECTION / ${p.no}</p><h3>${p.title}</h3><p>${p.copy}</p><div class="at-product-facts"><strong>${p.name}</strong><span>${p.note}</span><small>${p.disclosure}</small></div><a class="at-button at-button-dark" href="#/${p.id}">Explore ${p.category.toLowerCase()} ${arrow}</a><span class="at-price-note">Current prices & availability by enquiry</span></div>`;}
  function collection(){return `<section class="at-collection at-shell"><div class="at-section-heading"><div><p class="at-kicker">01 / FROM OUR FARM</p><h2>Good food.<br><em>Close to home.</em></h2></div><p>For your family. For your kitchen.<br>For the people you bring together.</p></div><div class="at-tabs" role="tablist" aria-label="Explore our products">${products.map((p,i)=>`<button role="tab" id="at-tab-${p.id}" aria-controls="at-product-panel" aria-selected="${i===0}" tabindex="${i===0?0:-1}" data-product-tab="${p.id}"><span>${p.no}</span>${p.category}<span aria-hidden="true">↗</span></button>`).join('')}</div><div id="at-product-panel" class="at-product-panel" role="tabpanel" aria-labelledby="at-tab-chicken">${panel(products[0])}</div></section>`;}
  document.querySelector('#home-template').innerHTML=`
  <section class="at-hero at-shell"><div class="at-hero-top"><p class="at-kicker"><span class="at-dot"></span> THE GAMBIA · EST. 2019</p><span>Community focused. Locally farmed.</span></div><div class="at-hero-layout"><div class="at-hero-copy"><h1>Good food.<br>Deep <em>roots.</em></h1><div class="at-hero-note"><span class="at-note-rule"></span><p>From a place we call home.<br>For the people who make it matter.</p></div><a class="at-button at-button-dark" href="#/products">Discover our products ${arrow}</a><a class="at-quiet-link" href="#/farm">Meet NemaFarms <span>→</span></a><div class="at-hero-signature"><img src="assets/logo.png" width="95" height="95" alt="NemaFarms established 2019"><p>Our land.<br>Our people.<br><em>Our possibility.</em></p></div></div><figure class="at-hero-visual"><img class="at-landscape" src="assets/farm-wide-1600.webp" srcset="assets/farm-wide-800.webp 800w, assets/farm-wide-1600.webp 1600w, assets/farm-wide.webp 2400w" sizes="(max-width:760px) 100vw, 58vw" width="2400" height="1800" alt="A person carrying a basin through the NemaFarms fields" fetchpriority="high"><div class="at-image-label"><span>FIELD NOTES / 001</span><span>LIFE ON THE FARM</span></div><a class="at-image-story" href="#/story"><span>A place.<br><em>A purpose.</em></span><span class="at-circle">↗</span></a><figcaption>THE GAMBIA, THROUGH OUR LENS <span>ORIGINAL FARM PHOTOGRAPH</span></figcaption></figure></div><div class="at-hero-baseline"><span>FOOD THAT BRINGS US TOGETHER</span><a href="#/approach">Rooted in something bigger <span>↓</span></a></div></section>
  <section class="at-purpose at-shell"><p class="at-kicker">A SIMPLE BELIEF</p><div><h2>A farm is more than<br>what it <em>grows.</em></h2><div class="at-purpose-bottom"><p>It is the people who tend it. The kitchens it reaches. And the future a community can build around good food. That is the idea at the heart of NemaFarms.</p><a class="at-circle" href="#/approach" aria-label="Read about our approach">↗</a></div></div></section>
  ${collection()}
  <section class="at-origin"><div class="at-origin-photo"><img src="assets/farm-work-1600.webp" width="1600" height="1200" alt="Growing work at NemaFarms" loading="lazy"><span>THE EVERYDAY WORK OF GROWING / NEMAFARMS</span></div><div class="at-origin-copy"><p class="at-kicker">02 / OUR COMMON GROUND</p><h2>Some things<br>start small.<br><em>And mean<br>everything.</em></h2><p>Established in 2019, NemaFarms is rooted in The Gambia and a belief in the value of local food, local work, and a shared future.</p><a class="at-button" href="#/farm">The story of our farm ${arrow}</a><div class="at-origin-foot"><span>2019</span><span>A BEGINNING.<br>A PURPOSE THAT CONTINUES.</span></div></div></section>
  <section class="at-proof-strip at-shell"><p class="at-kicker">HOW THE FARM GROWS</p><div><article><strong>Solar-powered</strong><span>Independent energy for the next chapter.</span></article><article><strong>Feed from the farm</strong><span>Corn and protein sources grown on the premises.</span></article><article><strong>Food forest</strong><span>Bananas, plantains, papayas, citrus, cocoa, guava and coffee.</span></article></div><a class="at-quiet-link" href="#/farm/how-we-grow">See how NemaFarms grows ${arrow}</a></section>
  <section class="at-trade at-shell"><div><p class="at-kicker">04 / GROWING YOUR BUSINESS, TOGETHER</p><h2>A place on<br><em>your menu.</em></h2><p>For restaurants, hotels, shops and kitchens with people to feed. Tell us what you need. Let’s begin there.</p><a class="at-button at-button-dark" href="#/wholesale">Talk wholesale ${arrow}</a></div><nav aria-label="Business enquiries"><a href="#/wholesale"><span>01</span><h3>Hospitality</h3><p>Hotels & guest houses</p>${arrow}</a><a href="#/wholesale"><span>02</span><h3>Food service</h3><p>Restaurants & kitchens</p>${arrow}</a><a href="#/wholesale"><span>03</span><h3>Retail</h3><p>Shops & local businesses</p>${arrow}</a></nav></section>
  <section class="at-story at-shell"><a class="at-story-photo" href="#/story?entry=land"><img src="assets/farm-wide-1600.webp" width="1600" height="1200" alt="A path through the NemaFarms landscape" loading="lazy"><span class="at-circle">↗</span></a><div><p class="at-kicker">THE JOURNAL / A PHOTO ESSAY</p><h2>Between the rows,<br><em>a story grows.</em></h2><p>Take a slower look at the place behind the produce.</p><a class="at-quiet-link" href="#/story?entry=land">Read the field notes ${arrow}</a></div></section>`;
  window.NemaPages.products=`<section class="at-catalog at-shell"><p class="at-kicker">NEMAFARMS / THE COLLECTION</p><h1>From the farm.<br><em>To your everyday.</em></h1><div><p>Whole chicken, egg crates and the growing fields.<br>Choose a product to explore, then speak directly with the farm.</p><a class="at-quiet-link" href="#/buying">How buying works ${arrow}</a></div></section>${collection()}<section class="at-catalog-end at-shell"><p class="at-kicker">PLANNING AHEAD?</p><h2>One kitchen.<br><em>Or a whole business.</em></h2><a class="at-button at-button-dark" href="#/wholesale">Explore wholesale ${arrow}</a></section>`;
  window.NemaPages.farm = window.NemaPages.farm.replace(/<section class="pg-intro pg-wrap">[\s\S]*?<\/figure>/, `<section class="at-farm-hero"><img src="assets/farm-wide.webp" width="2400" height="1800" alt="The landscape of NemaFarms in The Gambia" fetchpriority="high"><div class="at-shell"><p class="at-kicker">OUR FARM / THE GAMBIA</p><h1>A place to grow.<br><em>A reason to care.</em></h1><div class="at-farm-bottom"><p>Local land. Human work.<br>A purpose that reaches beyond the farm.</p><span>ESTABLISHED<br><strong>2019</strong></span></div></div></section>`);
  window.NemaPages.farm = window.NemaPages.farm.replace('<section class="pg-split pg-wrap">', `<section class="at-farm-systems at-shell" id="how-we-grow"><div class="at-systems-intro"><p class="at-kicker">HOW THE FARM GROWS</p><h2>Independent<br><em>by design.</em></h2><p>Our systems connect energy, feed and planting so the farm can keep building for the future.</p></div><article class="at-system-card"><img src="assets/solar-panels.jpg" alt="Solar panels in a field, stock photograph from Unsplash" loading="lazy"><div><p class="at-kicker">POWERED BY THE SUN</p><h3>Fully solarized.</h3><p>In our effort to build an independent and sustainable power grid, NemaFarms is fully solarized. The move to solar has resulted in remarkable cost reductions in our operations, while built-in redundancy anticipates our planned expansion.</p><small>Stock image: Unsplash · Green Voltaics Energy</small></div></article><article class="at-system-card at-system-forest"><img src="assets/client-produce-bed.webp" alt="A supplied photograph of a dense growing bed" loading="lazy"><div><p class="at-kicker">A DIVERSE FOOD FOREST</p><h3>More than a field.</h3><p>A small patch of the premises is dedicated to a remarkably diverse food forest with bananas, plantains, papayas, oranges, date palms, cocoa, guava and coffee.</p><small>Supplied NemaFarms photograph.</small></div></article></section><section class="pg-split pg-wrap">`);
  window.NemaPages.farm = window.NemaPages.farm.replace('<a class="pg-link" href="#/approach">Meet our approach ${arrow}</a>', '<a class="pg-link" href="#/farm/how-we-grow">How the farm grows ${arrow}</a>');
  window.NemaPages.farm = window.NemaPages.farm.replaceAll('#/approach', '#/farm/how-we-grow').replaceAll('#/farm#how-we-grow', '#/farm/how-we-grow').replaceAll('Meet our approach', 'How the farm grows');
  window.NemaPages.community = window.NemaPages.community.replace('These are directions for the future, rather than claims of completed expansion.', 'Our next chapter begins with the same commitment to people and place.');
  document.querySelector('#home-template').innerHTML = document.querySelector('#home-template').innerHTML.replaceAll('#/approach', '#/farm/how-we-grow').replaceAll('#/farm#how-we-grow', '#/farm/how-we-grow');
  window.NemaPages.products = window.NemaPages.products.replaceAll('#/buying', '#/wholesale');
  let quickDialog;
  function closeQuick(){quickDialog?.close();}
  document.addEventListener('click',event=>{
    const tab=event.target.closest('[data-product-tab]');
    if(tab){const section=tab.closest('.at-collection');section.querySelectorAll('[role="tab"]').forEach(t=>{t.setAttribute('aria-selected',String(t===tab));t.tabIndex=t===tab?0:-1});const target=section.querySelector('[role="tabpanel"]');target.setAttribute('aria-labelledby',tab.id);target.innerHTML=panel(products.find(p=>p.id===tab.dataset.productTab));if(!matchMedia('(prefers-reduced-motion: reduce)').matches)target.animate([{opacity:.3,transform:'translateY(8px)'},{opacity:1,transform:'none'}],{duration:350,easing:'ease-out'});window.ScrollTrigger?.refresh();}
    const quick=event.target.closest('[data-quick-product]');
    if(quick){const p=products.find(p=>p.id===quick.dataset.quickProduct);if(!quickDialog){quickDialog=document.createElement('dialog');quickDialog.className='at-quick-dialog';document.body.append(quickDialog);quickDialog.addEventListener('click',e=>{if(e.target===quickDialog||e.target.closest('[data-close-quick]'))closeQuick()});}quickDialog.setAttribute('aria-label',p.name);quickDialog.innerHTML=`<button class="at-dialog-close" data-close-quick aria-label="Close product view">Close ×</button><div class="at-quick-layout"><img src="assets/${p.image}" alt="${p.alt}" width="1122" height="1402"><div><p class="at-kicker">${p.category} / NEMAFARMS</p><h2>${p.name}</h2><p>${p.copy}</p><p class="at-small">${p.disclosure}</p><a class="at-button at-button-dark" href="#/${p.id}" data-close-quick>View product details ${arrow}</a><a class="at-quiet-link" href="tel:+2209176319">Call +220 917 6319 ${arrow}</a></div></div>`;quickDialog.showModal();window.NemaMotion?.gallery(quickDialog);}
  });
  document.addEventListener('keydown',e=>{if(!e.target.matches('[data-product-tab]')||!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();const tabs=[...e.target.parentElement.querySelectorAll('[role="tab"]')];let n=tabs.indexOf(e.target);n=e.key==='Home'?0:e.key==='End'?tabs.length-1:(n+(e.key==='ArrowRight'?1:-1)+tabs.length)%tabs.length;tabs[n].focus();tabs[n].click();});
  window.addEventListener('hashchange',closeQuick);
})();
