/* Expanded editorial and product-led design. */
(() => {
const productImage = '<img src="assets/chicken-studio.webp" alt="Studio treatment of the supplied NemaFarms packaged chicken photograph" width="1122" height="1402" loading="lazy">';
const cards = `<div class="v2-product-grid"><a class="v2-product-card" href="#/chicken"><div class="v2-card-image v2-chicken">${productImage}<span class="v2-product-tag">POULTRY</span></div><div class="v2-card-title"><h3>Whole chicken</h3><span>↗</span></div><p>A place at your table.</p></a><a class="v2-product-card" href="#/eggs"><div class="v2-card-image v2-egg-crate"><img src="assets/egg-crate.webp" width="1122" height="1402" alt="NemaFarms egg crate packaging concept with brown eggs and a cream branded band" loading="lazy"><span class="v2-product-tag">FARM EGGS</span></div><div class="v2-card-title"><h3>Egg crate</h3><span>↗</span></div><p>For the everyday rituals.</p></a><a class="v2-product-card" href="#/produce"><div class="v2-card-image"><img src="assets/farm-work-800.webp" alt="Growing fields at NemaFarms" width="800" height="600" loading="lazy"><span class="v2-product-tag">FROM THE FIELD</span></div><div class="v2-card-title"><h3>Farm produce</h3><span>↗</span></div><p>Ask what’s growing.</p></a></div>`;
document.getElementById('home-template').innerHTML = `
<section class="v2-hero"><img class="v2-hero-photo" src="assets/farm-wide-1600.webp" srcset="assets/farm-wide-800.webp 800w,assets/farm-wide-1200.webp 1200w,assets/farm-wide-1600.webp 1600w,assets/farm-wide.webp 2400w" sizes="100vw" width="2400" height="1800" alt="A person carrying a basin through the fields at NemaFarms" fetchpriority="high"><div class="v2-hero-content"><p class="eyebrow">NEMAFARMS · THE GAMBIA · EST. 2019</p><h1>From our land.<br>To your <em>table.</em></h1><p class="v2-hero-deck">Good food has a place it calls home.<br>Ours is The Gambia.</p><a class="v2-button" href="#/products">Explore our products <span>↗</span></a></div><a class="v2-hero-story" href="#/farm"><span>01 — OUR ROOTS</span><p>A farm with<br><em>a bigger purpose.</em></p><span class="v2-hero-story-arrow">↗</span></a><div class="v2-hero-bottom"><span>COMMUNITY FOCUSED. LOCALLY FARMED.</span><a href="#/gallery">A view from the farm ↓</a></div></section>
<div class="v2-ticker" aria-label="Our values"><span>Rooted in The Gambia</span><span aria-hidden="true">✳</span><span>Growing with purpose</span><span aria-hidden="true">✳</span><span>Community at heart</span><span aria-hidden="true">✳</span><span>Good food. Shared futures.</span></div>
<section class="v2-shop v2-shell"><div class="v2-section-head"><div><p class="eyebrow">A LITTLE CLOSER TO THE SOURCE</p><h2>From our farm.<br><em>For your everyday.</em></h2></div><a class="text-link" href="#/products">All our products <span>↗</span></a></div>${cards}<div class="v2-shop-bottom"><span>Availability and current prices are confirmed by enquiry.</span><a href="#/buying">A guide to buying from NemaFarms ↗</a></div></section>
<section class="v2-manifesto"><div class="v2-shell v2-manifesto-grid"><p class="eyebrow">THE REASON WE GROW</p><div><h2>Food brings us together.<br>The way we grow it<br><em>moves us forward.</em></h2><div class="v2-manifesto-bottom"><p>We believe in a prosperous, healthy Gambian food supply. In the value of local producers. And in a future shaped by the people who call this place home.</p><a class="round-link" href="#/approach" aria-label="Explore our approach">↗</a></div></div></div></section>
<section class="v2-roots v2-shell"><div class="v2-roots-photo"><img src="assets/farm-work-1200.webp" width="1200" height="900" alt="Everyday growing work at NemaFarms" loading="lazy"><span class="v2-photo-note">THE PEOPLE BEHIND THE GROWING</span></div><div class="v2-roots-copy"><p class="eyebrow">OUR STORY · SINCE 2019</p><h2>Some roots<br>run <em>deeper.</em></h2><p>A farm is a place. But it is also the people who tend it, the work that fills each day, and the community that gives it meaning.</p><p>This is where our story begins.</p><a class="text-link" href="#/farm">Get to know NemaFarms <span>↗</span></a><img class="v2-story-seal" src="assets/logo.png" alt="NemaFarms community focused, locally farmed" width="160" height="160"></div></section>
<section class="v2-business"><div class="v2-shell v2-business-inner"><div><p class="eyebrow">FOR KITCHENS, SHOPS & SHARED TABLES</p><h2>Good food.<br><em>Good company.</em></h2><p>Planning for a busy kitchen, a neighbourhood shop or a larger gathering? Let’s talk about what your business needs.</p><a class="v2-button" href="#/wholesale">Explore wholesale <span>↗</span></a></div><div class="v2-business-list"><a href="#/wholesale"><span>01</span>Hotels & hospitality<span>↗</span></a><a href="#/wholesale"><span>02</span>Restaurants & kitchens<span>↗</span></a><a href="#/wholesale"><span>03</span>Shops & retailers<span>↗</span></a><a href="#/partners"><span>04</span>Growers & partners<span>↗</span></a></div></div></section>
<section class="v2-journal v2-shell"><div class="v2-section-head"><div><p class="eyebrow">NOTES FROM NEMAFARMS</p><h2>Stories with<br><em>roots.</em></h2></div><a class="text-link" href="#/journal">The farm journal <span>↗</span></a></div><div class="v2-journal-grid"><a class="v2-journal-feature" href="#/story"><div class="v2-journal-image"><img src="assets/farm-wide-1200.webp" width="1200" height="900" alt="A path through NemaFarms" loading="lazy"></div><p class="eyebrow">PHOTO ESSAY · LIFE ON THE FARM</p><h3>The everyday work<br>of <em>growing.</em> <span>↗</span></h3></a><div class="v2-journal-links"><a href="#/community"><span class="eyebrow">PEOPLE & PURPOSE</span><h3>A future<br><em>worth sharing.</em></h3><span class="v2-journal-link-bottom">Our community ambition <span>↗</span></span></a><a href="#/gallery"><span class="eyebrow">THROUGH THE LENS</span><h3>A closer look<br><em>at farm life.</em></h3><span class="v2-journal-link-bottom">Explore the gallery <span>↗</span></span></a></div></div></section>
<section class="v2-close"><img src="assets/farm-wide-1600.webp" alt="The landscape around NemaFarms" width="1600" height="1200" loading="lazy"><div><p class="eyebrow">OUR LAND. OUR PEOPLE. OUR POSSIBILITY.</p><h2>Rooted here.<br><em>Growing tomorrow.</em></h2><a class="v2-button" href="#/community">Discover our purpose <span>↗</span></a></div></section>`;
window.NemaPages.products=`<section class="v2-catalog-head v2-shell"><p class="eyebrow">THE NEMAFARMS COLLECTION</p><h1>Good food.<br><em>Closer to home.</em></h1><div><p>From poultry to the growing fields. Explore what brings our farm and your table a little closer together.</p><a class="text-link" href="#/buying">How to buy <span>↗</span></a></div></section><section class="v2-shop v2-shell">${cards}<div class="v2-shop-bottom"><span>Ask the farm about current availability and prices.</span><a href="#/contact">Start a product enquiry ↗</a></div></section><section class="v2-business"><div class="v2-shell v2-business-inner"><div><p class="eyebrow">BUYING FOR YOUR BUSINESS?</p><h2>Let’s talk<br><em>about supply.</em></h2><p>Tell us about your products, quantities and timing. A clear conversation is the first step.</p><a class="v2-button" href="#/wholesale">Wholesale enquiries <span>↗</span></a></div><div class="v2-business-list"><a href="#/chicken">Whole chicken <span>↗</span></a><a href="#/eggs">Eggs <span>↗</span></a><a href="#/produce">Farm produce <span>↗</span></a></div></div></section>`;
})();
