(() => {
const arrow = '<span aria-hidden="true">↗</span>';
window.NemaPages = {
farm: `
<section class="pg-intro pg-wrap"><p class="pg-eyebrow">01 / Our farm · The Gambia</p><h1>A place to grow.<br><em>A reason to care.</em></h1><div class="pg-intro-bottom"><p>Our story begins with a simple belief: good food can help a community flourish.</p><span class="pg-small">ESTABLISHED 2019</span></div></section>
<figure class="pg-panorama"><img src="assets/farm-wide-1200.webp" srcset="assets/farm-wide-800.webp 800w, assets/farm-wide-1200.webp 1200w, assets/farm-wide-1600.webp 1600w, assets/farm-wide.webp 2400w" sizes="100vw" width="2400" height="1800" fetchpriority="high" alt="A person carrying a basin through the fields at NemaFarms"><figcaption>NemaFarms, The Gambia — a view from the field.</figcaption></figure>
<section class="pg-editorial pg-wrap"><p class="pg-eyebrow">The roots of Nema</p><div><h2>Local land.<br><em>Shared possibility.</em></h2><p>NemaFarms was established in 2019 with a community-focused vision for farming in The Gambia. At its heart is a commitment to local food supply and the people who make it possible.</p><p>That purpose shapes the story we want to tell: the everyday work of growing, the care behind raising poultry, and the connection between a farm and its community.</p></div></section>
<section class="pg-split pg-wrap"><figure><img src="assets/farm-work-1200.webp" srcset="assets/farm-work-800.webp 800w, assets/farm-work-1200.webp 1200w, assets/farm-work-1600.webp 1600w, assets/farm-work.webp 2400w" sizes="(max-width: 650px) 100vw, 60vw" width="2400" height="1800" loading="lazy" alt="A person tending plants at the farm"><figcaption>There is a person behind every day’s work.</figcaption></figure><div class="pg-split-copy"><p class="pg-eyebrow">People, before everything</p><h2>Growing is<br><em>human work.</em></h2><p>A farm is more than the land it occupies. It is the people who show up, the knowledge they share, and the communities they belong to.</p><p>Our mission connects the work in the fields and poultry houses with a shared ambition: strengthening food supply close to home.</p><a class="pg-link" href="#/approach">Meet our approach ${arrow}</a></div></section>
<section class="pg-banner"><div class="pg-wrap"><p class="pg-eyebrow">Looking ahead</p><h2>Rooted here.<br><em>Growing tomorrow.</em></h2><p>Our ambition is to strengthen local food supply and grow our community contribution. We will share progress as that work develops.</p><a class="pg-button" href="#/contact">Start a conversation ${arrow}</a></div></section>`,
products: `
<section class="pg-intro pg-wrap"><p class="pg-eyebrow">02 / From the farm</p><h1>Good food.<br><em>Close to home.</em></h1><div class="pg-intro-bottom"><p>Explore our farming focus, then talk with us about what is available and what you need.</p><a class="pg-link" href="#/contact">Enquire about supply ${arrow}</a></div></section>
<nav class="pg-product-nav pg-wrap" aria-label="Product categories"><a href="#/products/poultry">01 · Poultry <span>↓</span></a><a href="#/products/eggs">02 · Eggs <span>↓</span></a><a href="#/products/produce">03 · Produce <span>↓</span></a></nav>
<section class="pg-product pg-wrap" id="poultry"><figure><img src="assets/poultry-1200.webp" srcset="assets/poultry-800.webp 800w, assets/poultry-1200.webp 1200w, assets/poultry-1600.webp 1600w, assets/poultry.webp 2400w" sizes="(max-width: 650px) 100vw, 60vw" width="2400" height="1800" loading="lazy" alt="Poultry in the NemaFarms poultry house"><figcaption>A closer look at the farm’s poultry.</figcaption></figure><div><p class="pg-eyebrow">01 / Poultry</p><h2>Raised with<br><em>purpose.</em></h2><p>Poultry is part of the NemaFarms story. Whether you are buying for your household or exploring a supply relationship, begin with a conversation.</p><dl class="pg-facts"><div><dt>Availability</dt><dd>Confirm with the farm</dd></div><div><dt>Quantity & preparation</dt><dd>Discuss your requirements</dd></div><div><dt>Collection or delivery</dt><dd>Arranged by enquiry</dd></div></dl><a class="pg-button pg-button-dark" href="#/contact?product=Poultry">Enquire about poultry ${arrow}</a></div></section>
<section class="pg-product pg-product-alt pg-wrap" id="eggs"><div class="pg-type-art" aria-label="Eggs"><span class="pg-art-small">FROM THE FARM</span><img class="pg-brand-stamp" src="assets/logo.png" width="500" height="500" alt="NemaFarms — community-focused, locally farmed" loading="lazy"><span class="pg-art-word">Everyday<br><em>goodness.</em></span><span class="pg-art-small">NEMAFARMS · THE GAMBIA</span></div><div><p class="pg-eyebrow">02 / Eggs</p><h2>Simple food.<br><em>Everyday ritual.</em></h2><p>From a family breakfast to a busy kitchen, eggs have a place at the table. Get in touch to discuss current availability and the quantity you are looking for.</p><dl class="pg-facts"><div><dt>Availability</dt><dd>Confirm with the farm</dd></div><div><dt>Order size</dt><dd>Tell us what you need</dd></div></dl><a class="pg-button pg-button-dark" href="#/contact?product=Eggs">Enquire about eggs ${arrow}</a></div></section>
<section class="pg-product pg-wrap" id="produce"><figure><img src="assets/farm-work-1200.webp" srcset="assets/farm-work-800.webp 800w, assets/farm-work-1200.webp 1200w, assets/farm-work-1600.webp 1600w, assets/farm-work.webp 2400w" sizes="(max-width: 650px) 100vw, 60vw" width="2400" height="1800" loading="lazy" alt="Plants being tended at NemaFarms"><figcaption>In the fields at NemaFarms.</figcaption></figure><div><p class="pg-eyebrow">03 / Produce</p><h2>In season.<br><em>In conversation.</em></h2><p>The fields are part of a bigger ambition for locally grown food. Ask us about our current produce, seasonal plans, and opportunities to work together.</p><dl class="pg-facts"><div><dt>What’s growing</dt><dd>Ask for the current selection</dd></div><div><dt>Seasonality</dt><dd>Availability varies</dd></div></dl><a class="pg-button pg-button-dark" href="#/contact?product=Produce">Enquire about produce ${arrow}</a></div></section>
<section class="pg-banner"><div class="pg-wrap"><p class="pg-eyebrow">For kitchens, shops & partners</p><h2>Let’s find<br><em>common ground.</em></h2><p>Looking for an ongoing supply conversation? Tell us about your business, your quantities, and your timing.</p><a class="pg-button" href="#/contact?product=Wholesale">Discuss wholesale ${arrow}</a></div></section>`,
approach: `
<section class="pg-intro pg-wrap"><p class="pg-eyebrow">03 / Our approach</p><h1>More than growing.<br><em>Growing together.</em></h1><div class="pg-intro-bottom"><p>Community-focused. Locally farmed. A simple promise that gives our work its direction.</p><span class="pg-small">OUR VALUES, IN PRACTICE</span></div></section>
<section class="pg-approach-hero pg-wrap"><img src="assets/farm-work-1200.webp" srcset="assets/farm-work-800.webp 800w, assets/farm-work-1200.webp 1200w, assets/farm-work-1600.webp 1600w, assets/farm-work.webp 2400w" sizes="(max-width: 650px) 100vw, 60vw" width="2400" height="1800" loading="lazy" alt="Working among the plants at NemaFarms"><div class="pg-quote"><p>“Community-focused,<br><em>locally farmed.”</em></p><span>The NemaFarms identity</span></div></section>
<section class="pg-principles pg-wrap"><div class="pg-principle"><span>01</span><h2>Begin with<br><em>community.</em></h2><p>Our mission puts local people and local food supply at the center. As the farm develops, that purpose remains our reference point.</p></div><div class="pg-principle"><span>02</span><h2>Stay close<br><em>to the land.</em></h2><p>Every day of farming begins with the land and the work it asks of us. Our approach keeps that relationship close, from tending plants to raising poultry.</p></div><div class="pg-principle"><span>03</span><h2>Grow with<br><em>intention.</em></h2><p>Our plans look toward a stronger contribution to food supply in The Gambia, guided by our commitment to local farming and community.</p></div></section>
<section class="pg-editorial pg-wrap pg-top-rule"><p class="pg-eyebrow">A living story</p><div><h2>Good questions<br><em>make good beginnings.</em></h2><p>Want to understand the farm, explore a supply relationship, or discuss a shared idea? A direct conversation is the best place to start.</p><a class="pg-link" href="#/contact">Talk with NemaFarms ${arrow}</a></div></section>`,
contact: `
<section class="pg-intro pg-wrap"><p class="pg-eyebrow">04 / Get in touch</p><h1>There’s room<br><em>for conversation.</em></h1><div class="pg-intro-bottom"><p>A question about the farm, an enquiry about supply, or an idea worth sharing. Start here.</p><span class="pg-small">NEMAFARMS · THE GAMBIA</span></div></section>
<section class="pg-contact pg-wrap"><aside><p class="pg-eyebrow">Let’s connect</p><h2>Good things<br><em>start small.</em></h2><p>Tell us what you have in mind. Include quantities and timing if you are enquiring about products or wholesale supply.</p><div class="pg-contact-note"><span class="pg-small">A NOTE ON THIS PREVIEW</span><p>This form demonstrates the enquiry experience. Nothing is sent. Contact details will be confirmed before launch.</p></div><img class="pg-contact-photo" src="assets/farm-wide-1200.webp" srcset="assets/farm-wide-800.webp 800w, assets/farm-wide-1200.webp 1200w, assets/farm-wide-1600.webp 1600w, assets/farm-wide.webp 2400w" sizes="(max-width: 650px) 100vw, 60vw" width="2400" height="1800" loading="lazy" alt="A path through the fields at NemaFarms"></aside>
<form class="pg-form" data-enquiry-form><div class="pg-form-heading"><p class="pg-eyebrow">Your enquiry</p><span>01 — A little about you</span></div><div class="pg-form-row"><div><label for="enquiry-name">Your name <span aria-hidden="true">*</span></label><input id="enquiry-name" name="name" autocomplete="name" placeholder="Full name" required></div><div><label for="enquiry-contact">Email or phone <span aria-hidden="true">*</span></label><input id="enquiry-contact" name="contact" placeholder="How we can reach you" required></div></div><label for="enquiry-product">What brings you here?</label><select id="enquiry-product" name="product"><option value="General enquiry">General enquiry</option><option value="Poultry">Poultry</option><option value="Whole chicken">Whole chicken</option><option value="Eggs">Eggs</option><option value="Egg crate">Egg crate</option><option value="Produce">Produce</option><option value="Wholesale">Wholesale supply</option><option value="Partnership">Partnership</option></select><div class="pg-form-row"><div><label for="enquiry-quantity">Approximate quantity</label><input id="enquiry-quantity" name="quantity" placeholder="e.g. 12 whole chickens"></div><div><label for="enquiry-business">Business name (optional)</label><input id="enquiry-business" name="business" autocomplete="organization" placeholder="Your business"></div></div><label for="enquiry-message">A little more detail <span aria-hidden="true">*</span></label><textarea id="enquiry-message" name="message" rows="5" placeholder="Tell us what you need, and when…" required></textarea><p class="pg-form-help">Design preview only. Your enquiry will be shown on this page for review; it will not be submitted.</p><button class="pg-button pg-button-dark" type="submit">Preview enquiry ${arrow}</button><div class="pg-form-result" data-enquiry-result role="status" aria-live="polite"></div></form></section>`
};
})();
